### ISSUE TITLE
The Box Model of Website Styling

### ISSUE THREAD

**Issue by nuranurbekova** [BrightBrainsKk/Section-5-Intermediate-CSS#1]
1. Посмотреть видео
2. Написать код
3. Снять видео
4. Загрузить

**Comment by Ainurjanybekovna** [comment]
[mysite.zip](https://github.com/BrightBrainsKk/Section-5-Intermediate-CSS/files/7008582/mysite.zip)
Видео корулду
Код жазылды
Видео тартылды
Загрузка болду
