### ISSUE TITLE
The Dark Art of Centering Elements with CSS

### ISSUE THREAD

**Issue by nuranurbekova** [BrightBrainsKk/Section-5-Intermediate-CSS#11]
1. Посмотреть и снять видео
2. Написать код и загрузить

**Comment by alimbaeva** [comment]
[my-site-2.zip](https://github.com/BrightBrainsKk/Section-5-Intermediate-CSS/files/7006499/my-site-2.zip)
Сложности с фотографиями и позиционированием было.
