### ISSUE TITLE
HTML Divs

### ISSUE THREAD

**Issue by nuranurbekova** [BrightBrainsKk/Section-5-Intermediate-CSS#4]
1. Посмотреть видео
2. Написать код
3.  Снять видео
4. Загрузить

**Comment by ShahzadaMamatisaeva** [comment]
[HTML Divs.zip](https://github.com/BrightBrainsKk/Section-5-Intermediate-CSS/files/7002316/HTML.Divs.zip)
1. Посмотрела
2. Написала
3. Сняла и загрузила на общую почту в гугл
4. Загрузила. 
5. Сделано! Для выполнения этого задания ушло 2 дня). Самое сложное это сконцентрироваться во время записи видео урока! 
[HTML Divs.zip](https://github.com/BrightBrainsKk/Section-5-Intermediate-CSS/files/7002331/HTML.Divs.zip)

**Comment by ShahzadaMamatisaeva** [comment]
[Uploading HTML Divs.zip…]()
