### ISSUE TITLE
What We'll Make - Stylised Personal Site Linked pull requests

### ISSUE THREAD

**Issue by nuranurbekova** [BrightBrainsKk/Section-5-Intermediate-CSS#5]
Посмотреть и снять видео, а также написать код и загрузить.

**Comment by alimbaeva** [comment]
[css-my-site (2).zip](https://github.com/BrightBrainsKk/Section-5-Intermediate-CSS/files/7006482/css-my-site.2.zip)
я соединила 2 темы 1 и 2.
