### ISSUE TITLE
CSS Display Property

### ISSUE THREAD

**Issue by nuranurbekova** [BrightBrainsKk/Section-5-Intermediate-CSS#7]
1. Посмотреть и снять видео
2. Написать код и загрузить

**Comment by AiperiAbdygazykyzy** [comment]
Жеке код жазуу кыйынга турган жок. Бирок, тушунугумду жазып, видео сабак тартуу менен биргеликте аны тушундуруп айтып берууго жалпы бир кун кетти.

**Comment by AiperiAbdygazykyzy** [comment]
[Css Display property.zip](https://github.com/BrightBrainsKk/Section-5-Intermediate-CSS/files/7025177/Css.Display.property.zip)

**Comment by AiperiAbdygazykyzy** [comment]
Жеке код жазуу кыйынга турган жок. Бирок, тушунугумду жазып, видео сабак тартуу менен биргеликте аны тушундуруп айтып берууго жалпы бир кун кетти.
[Css Display property.zip](https://github.com/BrightBrainsKk/Section-5-Intermediate-CSS/files/7025199/Css.Display.property.zip)
