### ISSUE TITLE
Font Styling in Our Personal Site

### ISSUE THREAD

**Issue by nuranurbekova** [BrightBrainsKk/Section-5-Intermediate-CSS#8]
1. Посмотреть и снять видео
2. Написать код и загрузить

**Comment by AiperiAbdygazykyzy** [comment]
Шрифттер жана алардын келип чыгышы тууралуу маалыматтар абдан кызыктуу болду, жана аларды колдонуп код жазып айтып беруу эч кандай кыйынчылык жараткан жок.

**Comment by AiperiAbdygazykyzy** [comment]
[Font styling in our personal site.zip](https://github.com/BrightBrainsKk/Section-5-Intermediate-CSS/files/7025165/Font.styling.in.our.personal.site.zip)

**Comment by AiperiAbdygazykyzy** [comment]
Шрифттер жана алардын келип чыгышы тууралуу маалыматтар абдан кызыктуу болду, жана аларды колдонуп код жазып айтып беруу эч кандай кыйынчылык жараткан жок.
[Font styling in our personal site.zip](https://github.com/BrightBrainsKk/Section-5-Intermediate-CSS/files/7025201/Font.styling.in.our.personal.site.zip)
